server:
  port: 8085

spring:
  r2dbc:
    url: r2dbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres
    username: postgres.axjiwuvnxdvhklskznoh
    password: hackaton2025!
    pool:
      initial-size: 5
      max-size: 20
